name = "portfolio-tech"
compatibility_date = "2024-01-01"

[assets]
directory = "./dist"

[env.production]
name = "stylish-portfolio-site"

[[env.production.pages]]
project_name = "stylish-portfolio-site"
production_branch = "main" 